var en_lang = {
	about: "About",
	addItemsMsg: "Please add some items by clicking here.",
	addNewItem: "Add new item",
	alreadyExists: "already exists.",
	alreadyFull: "There are already 8 items registered. You cannot add any more until you delete some.",
	backBtnText: "Back",
	cancelBtnText: "Cancel",
	deleteBtnText: "Delete",
	descriptionPlaceholder: "Description",
	editItems: "Edit items",
	errorText: "Error!",
	home: "Home",
	howStartMsg: "In order to start keeping track of your expenses please add some items.",
	item: "Item",
	itemNameAtLeastThreeChars: "Item's name has to be at least 3 characters.",
	itemNameNoLongerThanTwentyChars: "Item's name cannot be longer than 20 characters.",
	itemNamePlaceholder: "Item's name (Required)",
	itemNameRequired: "Item's name is required.",
	noExpensesFound: "No expenses found for",
	noItemsFoundMsg: "No items found.",
	notificationSettingHeader: "Notify when cleaning older entries",
	notificationSettingMsg: "User is notified before older entries are deleted.",
	offBtnText: "OFF",
	onBtnText: "ON",
	other: "Other",
	priceNoNumberMsg: "Item's price should be a number.",
	pricePlaceholder: "Default price, e.g. 12.20",
	priceRequiredMsg: "Item's price is required.",
	priceRequiredPlaceholder: "Default price (Required), e.g. 12.20",
	registerBtnText: "Register",
	saveBtnText: "Save",
	saveAndAddAnotherBtnText: "Save and add another",
	selectCategory: "Select category",
	selectMonth: "Select month",
	settings: "Settings",
	showExpenses: "Show expenses",
	smartPlacementHeader: "Smart placement",
	smartPlacementMsg: "Re-arranges the items based on patterns of usage.",
	totalFor: "Total for",
	updateBtnText: "Update",
	welcomeMsg: "Welcome to XpenseMe!"
};