var en_lang = {
	about: "About",
	added: "added",
	addItemsMsg: "Please add some items by clicking here.",
	addNewItem: "Add new item",
	alreadyExists: "already exists.",
	alreadyFull: "There are already 8 items registered. You cannot add any more until you delete some.",
	backBtnText: "Back",
	bills: "Bills",
	book: "Book",
	cancelBtnText: "Cancel",
	cleaning: "Cleaning",
	clothing: "Clothing",
	coffee: "Coffee",
	deleteBtnText: "Delete",
	deleted: "deleted",
	descriptionPlaceholder: "Description",
	drink: "Drink",
	editItems: "Edit items",
	electronics: "Electronics",
	errorText: "Error!",
	expenses: "Expenses",
	exportAllExpensesBtnText: "Export all",
	exportCurrentMonthBtnText: "Export selected",
	food: "Food",
	gas: "Gas",
	home: "Home",
	howStartMsg: "In order to start keeping track of your expenses please add some items.",
	item: "Item",
	itemNameAtLeastThreeChars: "Item's name has to be at least 3 characters.",
	itemNameNoLongerThanTwentyChars: "Item's name cannot be longer than 20 characters.",
	itemNamePlaceholder: "Item's name (Required)",
	itemNameRequired: "Item's name is required.",
	months: [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December"
	],
	movies: "Movies",
	music: "Music",
	noExpensesFound: "No expenses found for",
	noItemsFoundMsg: "No items found.",
	noneOfTheAbove: "None of the above",
	notificationSettingHeader: "Notify when cleaning older entries",
	notificationSettingMsg: "User is notified before older entries are deleted.",
	offBtnText: "OFF",
	onBtnText: "ON",
	other: "Other",
	pets: "Pets",
	priceFor: "Price for ",
	priceNoNumberMsg: "Item's price should be a number.",
	pricePlaceholder: "Default price, e.g. 12.20",
	priceRequiredMsg: "Item's price is required.",
	priceRequiredPlaceholder: "Default price (Required), e.g. 12.20",
	registerBtnText: "Register",
	registered: "registered",
	saveBtnText: "Save",
	saveAndAddAnotherBtnText: "Save and add another",
	selectCategory: "Select category",
	selectMonth: "Select month",
	settings: "Settings",
	shopping: "Shopping",
	showExpenses: "Show expenses",
	smartPlacementHeader: "Smart placement",
	smartPlacementMsg: "Re-arranges the items based on patterns of usage.",
	smoking: "Smoking",
	sports: "Sports",
	totalFor: "Total for",
	transportation: "Transportation",
	travelling: "Travelling",
	updateBtnText: "Update",
	updated: "updated",
	welcomeMsg: "Welcome to XpenseMe!"
};