var gr_lang = {
	about: "Πληροφορίες",
	addItemsMsg: "Μπορείτε να προσθέσετε αντικείμενα πατώντας εδώ.",
	addNewItem: "Πρόσθεση νέου αντικειμένου",
	alreadyExists: "υπάρχει ήδη.",
	alreadyFull: "Υπάρχουν ήδη 8 αντικείμενα καταχωρημένα. Δεν μπορείτε να προσθέσετε άλλα αν δεν διαγράψετε κάποια από τα υπάρχοντα.",
	backBtnText: "Πίσω",
	cancelBtnText: "Ακύρωση",
	deleteBtnText: "Διαγραφή",
	descriptionPlaceholder: "Περιγραφή",
	editItems: "Διαχείριση αντικειμένων",
	errorText: "Λάθος!",
	home: "Αρχική σελίδα",
	howStartMsg: "Ξεκινώντας, προσθέστε κάποια αντικείμενα που αγοράζετε συχνά.",
	item: "Το αντικείμενο",
	itemNameAtLeastThreeChars: "Το όνομα του αντικειμένου πρέπει να έχει τουλάχιστον 3 γράμματα.",
	itemNameNoLongerThanTwentyChars: "Το όνομα του αντικειμένου δεν μπορεί να έχει περισσότερα από 20 γράμματα.",
	itemNamePlaceholder: "Όνομα αντικειμένου (υποχρεωτικό πεδίο)",
	itemNameRequired: "Το όνομα του αντικειμένου είναι υποχρεωτικό πεδίο.",
	noExpensesFound: "Δεν βρέθηκαν έξοδα για",
	noItemsFoundMsg: "Δεν βρέθηκαν αντικείμενα.",
	notificationSettingHeader: "Notify when cleaning older entries",
	notificationSettingMsg: "Ο χρήστης ειδοποιείται πριν διαγραφούν παλιά έξοδα.",
	offBtnText: "ΟΧΙ",
	onBtnText: "ΝΑΙ",
	other: "Άλλο",
	priceNoNumberMsg: "Η τιμή του αντικειμένου πρέπει να είναι αριθμός.",
	pricePlaceholder: "Τιμή αντικειμένου, π.χ. 12.20",
	priceRequiredMsg: "Η τιμή του αντικειμένου είναι υποχρεωτικό πεδίο.",
	priceRequiredPlaceholder: "Τιμή (Υποχρεωτικό πεδίο), π.χ. 12.20",
	registerBtnText: "Καταχώρηση",
	saveBtnText: "Αποθήκευση",
	saveAndAddAnotherBtnText: "Αποθήκευση και πρόσθεση επόμενου",
	selectCategory: "Επιλέξτε κατηγορία",
	selectMonth: "Επιλέξτε μήνα",
	settings: "Ρυθμίσεις",
	showExpenses: "Έξοδα",
	smartPlacementHeader: "Έξυπνη τοποθέτηση",
	smartPlacementMsg: "Αυτόματη αναδιακατανομή των αντικειμένων βασιζόμενη σε μοτίβα χρήσης.",
	totalFor: "Σύνολο για",
	updateBtnText: "Ανανέωση",
	welcomeMsg: "Καλωσήρθατε στο XpenseMe!"
};